---
branding:
  color: blue
  icon: anchor

description: >-
  Starts the docker compose services.

name: Start Docker Compose

runs:
  steps:
    - name: Setup Buildx
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3

    - env:
        COMPOSE_DOCKER_CLI_BUILD: "1"
        DOCKER_BUILDKIT: "1"
      name: Start Containers
      run: docker compose up --detach
      shell: bash

  using: composite
