---
branding:
  color: blue
  icon: anchor

description: >-
  Starts the docker compose services.

name: Start Docker Compose

runs:
  steps:
    - name: Setup Buildx
      uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3

    - env:
        COMPOSE_DOCKER_CLI_BUILD: "1"
        DOCKER_BUILDKIT: "1"
      name: Start Containers
      run: docker compose up --detach
      shell: bash

  using: composite
