---
branding:
  color: blue
  icon: anchor

description: >-
  Starts the docker compose services.

name: Start Docker Compose

runs:
  steps:
    - name: Setup Buildx
      uses: docker/setup-buildx-action@8026d2bc3645ea78b0d2544766a1225eb5691f89 # v3

    - env:
        COMPOSE_DOCKER_CLI_BUILD: "1"
        DOCKER_BUILDKIT: "1"
      name: Start Containers
      run: docker compose up --detach
      shell: bash

  using: composite
