---

version: "3"

services:
  cockroach:
    build:
      context: ./priv/cockroachdb
    entrypoint: /cockroach/start-insecure-local.sh
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - cockroach:/cockroach/cockroach-data

volumes:
  cockroach:
