---

version: "3"

services:
  cockroach:
    image: docker.io/cockroachdb/cockroach:latest
    command: start-single-node --accept-sql-without-tls
    environment:
      COCKROACH_USER: jumar
      COCKROACH_PASSWORD: jumar
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - cockroach:/cockroach/cockroach-data

volumes:
  cockroach:
