---

# Linter rules doc:
# - https://yamllint.readthedocs.io/en/stable/rules.html
#
# Note:
# To comment out a single line:
# # yamllint disable-line

locale: "en_US.UTF-8"

rules:
  braces:
    level: warning
    max-spaces-inside: 0
    max-spaces-inside-empty: 5
    min-spaces-inside: 0
    min-spaces-inside-empty: 0
  brackets:
    level: warning
    max-spaces-inside: 0
    max-spaces-inside-empty: 5
    min-spaces-inside: 0
    min-spaces-inside-empty: 1
  colons:
    level: warning
    max-spaces-after: 1
    max-spaces-before: 0
  commas:
    level: warning
    max-spaces-after: 1
    max-spaces-before: 0
    min-spaces-after: 1
  comments:
    ignore-shebangs: true
    min-spaces-from-content: 1
    require-starting-space: true
  comments-indentation: {}
  document-end: disable
  document-start:
    level: warning
    present: true
  empty-lines:
    level: warning
    max: 2
    max-end: 0
    max-start: 1
  hyphens:
    level: warning
    max-spaces-after: 1
  indentation:
    check-multi-line-strings: false
    indent-sequences: true
    level: warning
    spaces: 2
  key-duplicates: {}
  key-ordering: {}
  line-length:
    allow-non-breakable-inline-mappings: true
    allow-non-breakable-words: true
    ignore: |
      *.github*
    level: warning
    max: 80
  new-line-at-end-of-file: {}
  new-lines:
    type: unix
  trailing-spaces: {}
