---

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Build Docs
        run: mix docs

  Format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Format
        run: mix format --check-formatted

  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint
        uses: github/super-linter/slim@v4

  Lint_Actions:
    name: Lint (Actions)
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint
        uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: github-pr-review

  Lint_Alex:
    name: Lint (Alex)
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint
        uses: reviewdog/action-alex@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: github-pr-review

  Lint_Javascript:
    name: Lint (Javascript)
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Standard
        run: npm install eslint-config-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-n

      - name: Lint
        uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: --config .github/linters/.eslintrc.json .
          fail_on_error: true
          filter_mode: nofilter
          reporter: github-pr-review

  Lint_Language:
    name: Lint (Language)
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint
        uses: reviewdog/action-languagetool@v1
        with:
          disabled_categories: ""
          disabled_rules: ""
          fail_on_error: true
          filter_mode: nofilter
          reporter: github-pr-review

  Lint_Markdown:
    name: Lint (Markdown)
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint
        uses: reviewdog/action-markdownlint@v0
        with:
          fail_on_error: true
          filter_mode: nofilter
          markdownlint_flags: --config .github/linters/.markdown-lint.yml .
          reporter: github-pr-review

  Lint_Misspell:
    name: Lint (Misspell)
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint
        uses: reviewdog/action-misspell@v1
        with:
          exclude: |
            ./.git/*
          fail_on_error: true
          filter_mode: nofilter
          locale: US
          reporter: github-pr-review

  Lint_Yaml:
    name: Lint (Yaml)
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint
        uses: reviewdog/action-yamllint@v1
        with:
          eslint_flags: -c .github/linters/.yaml-lint.yml .
          fail_on_error: true
          filter_mode: nofilter
          reporter: github-pr-review

  Sobelow:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Sobelow
        uses: sobelow/action@v1

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Docker Compose
        uses: ./.github/actions/start-docker-compose

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Compile
        run: mix compile --all-warnings --warnings-as-errors

      - name: Test
        run: mix test --all-warnings --cover --warnings-as-errors
