---
jobs:
  Benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Cache Results
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          key: benchmarks
          path: benchmark_results

      - name: Start Docker Compose
        uses: ./.github/actions/start-docker-compose

      - name: Benchmark
        run: mix benchmark

  Build_Documentation:
    name: Build (Documentation)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Build Docs
        run: mix docs --warnings-as-errors

  Format_Elixir:
    name: Format (Elixir)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Format
        run: mix format ${{ github.event_name == 'pull_request' && '' || '--check-formatted' }}

      - if: ${{ github.event_name == 'pull_request' }}
        name: Suggest
        uses: reviewdog/action-suggester@aa38384ceb608d00f84b4690cacc83a5aba307ff # v1
        with:
          fail_level: any
          filter_mode: nofilter
          tool_name: mix

  Lint_Actions:
    name: Lint (Actions)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Lint
        uses: reviewdog/action-actionlint@95395aac8c053577d0bc67eb7b74936c660c6f66 # v1
        with:
          fail_level: any
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Alex:
    name: Lint (Alex)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Lint
        uses: reviewdog/action-alex@6083b8ca333981fa617c6828c5d8fb21b13d916b # v1
        with:
          filter_mode: ${{ github.event_name == 'pull_request' && 'added' || 'nofilter' }}
          level: info
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_CSS:
    name: Lint (CSS)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Stylelint
        run: npm install stylelint stylelint-config-standard

      - name: Lint
        uses: reviewdog/action-stylelint@dd2b435cc6a7c82705307a9dee740c9bbaa10411 # v1
        with:
          fail_level: any
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}
          stylelint_config: .github/linters/.stylelintrc.json

  Lint_Credo:
    name: Lint (Credo)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Credo
        run: mix credo

  Lint_Dialyzer:
    name: Lint (Dialyzer)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Dialyzer
        run: mix dialyzer

  Lint_Docker:
    name: Lint (Docker)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Lint
        uses: reviewdog/action-hadolint@fc7ee4a9f71e521bc43e370819247b70e5327540 # v1
        with:
          fail_level: any
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Doctor:
    name: Lint (Doctor)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Doctor
        run: mix doctor

  Lint_Javascript:
    name: Lint (Javascript)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Standard
        run: npm install eslint-config-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-n

      - name: Lint
        uses: reviewdog/action-eslint@556a3fdaf8b4201d4d74d406013386aa4f7dab96 # v1
        with:
          eslint_flags: --config .github/linters/.eslintrc.json .
          fail_level: any
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Markdown:
    name: Lint (Markdown)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Lint
        uses: reviewdog/action-markdownlint@3667398db9118d7e78f7a63d10e26ce454ba5f58 # v0
        with:
          fail_level: any
          filter_mode: nofilter
          markdownlint_flags: -c .github/linters/.markdown-lint.yml .
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Misspell:
    name: Lint (Misspell)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Lint
        uses: reviewdog/action-misspell@9daa94af4357dddb6fd3775de806bc0a8e98d3e4 # v1
        with:
          fail_level: any
          filter_mode: nofilter
          ignore: behaviour
          locale: US
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Shellcheck:
    name: Lint (Shellcheck)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Lint
        uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1
        with:
          fail_level: any
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Shfmt:
    name: Lint (shfmt)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Lint
        uses: reviewdog/action-shfmt@d8f080930b9be5847b4f97e9f4122b81a82aaeac # v1
        with:
          fail_on_error: true
          filter_mode: nofilter

  Lint_Yaml:
    name: Lint (Yaml)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Lint
        uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0 # v1
        with:
          fail_level: any
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}
          yamllint_flags: -c .github/linters/.yaml-lint.yml .

  Security_Sobelow:
    name: Security (Sobelow)
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Compile
        run: mix compile

      - name: Sobelow
        run: mix sobelow

      # We run once to allow any compile warnings or things that
      # would interfere with the JSON output
      - name: Sobelow Sarif
        run: mix sobelow --skip --format sarif > results.sarif

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3 # v3
        with:
          sarif_file: results.sarif

  Test:
    env:
      MIX_ENV: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Compile
        run: mix compile --all-warnings --warnings-as-errors

      - name: Start Docker Compose
        uses: ./.github/actions/start-docker-compose

      - name: Test
        run: mix test --all-warnings --cover --warnings-as-errors

name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
