---
jobs:
  Benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Cache Results
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          key: benchmarks
          path: benchmark_results

      - name: Start Docker Compose
        uses: ./.github/actions/start-docker-compose

      - name: Benchmark
        run: mix benchmark

  Docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Build Docs
        run: mix docs

  Format_Elixir:
    name: Format (Elixir)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Format
        run: mix format ${{ github.event_name == 'pull_request' && '' || '--check-formatted' }}

      - if: ${{ github.event_name == 'pull_request' }}
        name: Suggest
        uses: reviewdog/action-suggester@951f8ea45137fd52d269d75bddc3a813b78487aa # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          tool_name: mix

  Lint_Actions:
    name: Lint (Actions)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-actionlint@d99f1ceaf59e7db022a790dc308ccccb68dda71a # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Alex:
    name: Lint (Alex)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-alex@95457e9fb31e708d898774ca8e25be56d0766e84 # v1
        with:
          filter_mode: ${{ github.event_name == 'pull_request' && 'added' || 'nofilter' }}
          level: info
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_CSS:
    name: Lint (CSS)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install Stylelint
        run: npm install stylelint stylelint-config-standard

      - name: Lint
        uses: reviewdog/action-stylelint@31c9258e67acde86086d6bf56e1d46e124eaa3c3 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}
          stylelint_config: .github/linters/.stylelintrc.json

  Lint_Credo:
    name: Lint (Credo)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Credo
        run: mix credo

  Lint_Docker:
    name: Lint (Docker)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-hadolint@15df5a025251f3b06814d53ba1e782f5a42b2874 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Doctor:
    name: Lint (Doctor)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Doctor
        run: mix doctor

  Lint_Javascript:
    name: Lint (Javascript)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install Standard
        run: npm install eslint-config-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-n

      - name: Lint
        uses: reviewdog/action-eslint@7b82dea8533d382fa3c6ef95bcb1f1004f6b0a95 # v1
        with:
          eslint_flags: --config .github/linters/.eslintrc.json .
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Markdown:
    name: Lint (Markdown)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-markdownlint@af20b94e5c376c5b964555d9c21c2d9df8b89975 # v0
        with:
          fail_on_error: true
          filter_mode: nofilter
          markdownlint_flags: -c .github/linters/.markdown-lint.yml .
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Misspell:
    name: Lint (Misspell)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-misspell@278e1b3c7dd09d2827fa080919a40db73ccafe24 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          locale: US
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Shellcheck:
    name: Lint (Shellcheck)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-shellcheck@628ce8561be20bfbfb6173cf88c7475ddab95f22 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Shfmt:
    name: Lint (shfmt)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-shfmt@f59386f08bd9a24ac1a746e69f026ddc2ed06710 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter

  Lint_Yaml:
    name: Lint (Yaml)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-yamllint@c23c5d4cd45b5cc16fa3e6e34073068b228cabeb # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}
          yamllint_flags: -c .github/linters/.yaml-lint.yml .

  Sobelow:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Compile
        run: mix compile

      - name: Sobelow
        run: mix sobelow

      # We run once to allow any compile warnings or things that
      # would interfere with the JSON output
      - name: Sobelow Sarif
        run: mix sobelow --format sarif > results.sarif

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@b611370bb5703a7efb587f9d136a52ea24c5c38c # v3
        with:
          sarif_file: results.sarif

  Test:
    env:
      MIX_ENV: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Compile
        run: mix compile --all-warnings --warnings-as-errors

      - name: Start Docker Compose
        uses: ./.github/actions/start-docker-compose

      - name: Test
        run: mix test --all-warnings --cover --warnings-as-errors

name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
