---
jobs:
  Benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Cache Results
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          key: benchmarks
          path: benchmark_results

      - name: Start Docker Compose
        uses: ./.github/actions/start-docker-compose

      - name: Benchmark
        run: mix benchmark

  Docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Build Docs
        run: mix docs

  Format_Elixir:
    name: Format (Elixir)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Format
        run: mix format ${{ github.event_name == 'pull_request' && '' || '--check-formatted' }}

      - if: ${{ github.event_name == 'pull_request' }}
        name: Suggest
        uses: reviewdog/action-suggester@185c9c06d0a28fbe43b50aca4b32777b649e7cbd # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          tool_name: mix

  Lint_Actions:
    name: Lint (Actions)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Lint
        uses: reviewdog/action-actionlint@fd627997c9688c2f39e13917aed23873c031b834 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Alex:
    name: Lint (Alex)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Lint
        uses: reviewdog/action-alex@0f066ba775156b3c630e560b0304ed0d7a12b796 # v1
        with:
          filter_mode: ${{ github.event_name == 'pull_request' && 'added' || 'nofilter' }}
          level: info
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_CSS:
    name: Lint (CSS)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Install Stylelint
        run: npm install stylelint stylelint-config-standard

      - name: Lint
        uses: reviewdog/action-stylelint@0bea45384d07c94df70f326b75c38e4c9ddbacb8 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}
          stylelint_config: .github/linters/.stylelintrc.json

  Lint_Credo:
    name: Lint (Credo)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Credo
        run: mix credo

  Lint_Docker:
    name: Lint (Docker)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Lint
        uses: reviewdog/action-hadolint@0cb2ac2bb3969115db5f40c88bbb1f4ce7f59c2f # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Doctor:
    name: Lint (Doctor)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Doctor
        run: mix doctor

  Lint_Javascript:
    name: Lint (Javascript)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Install Standard
        run: npm install eslint-config-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-n

      - name: Lint
        uses: reviewdog/action-eslint@790a3d311c34b6f73294740617f9c2e9be493ae3 # v1
        with:
          eslint_flags: --config .github/linters/.eslintrc.json .
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Markdown:
    name: Lint (Markdown)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Lint
        uses: reviewdog/action-markdownlint@5bc6ad5ba9e1250878f351bafcc7ac0a11dc050f # v0
        with:
          fail_on_error: true
          filter_mode: nofilter
          markdownlint_flags: -c .github/linters/.markdown-lint.yml .
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Misspell:
    name: Lint (Misspell)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Lint
        uses: reviewdog/action-misspell@a8d48353ad85f5e20d5a5d86549245a30c21f74f # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          locale: US
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Shellcheck:
    name: Lint (Shellcheck)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Lint
        uses: reviewdog/action-shellcheck@72365a51bf6476fe952a117c3ff703eb7775e40a # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Shfmt:
    name: Lint (shfmt)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Lint
        uses: reviewdog/action-shfmt@f59386f08bd9a24ac1a746e69f026ddc2ed06710 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter

  Lint_Yaml:
    name: Lint (Yaml)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Lint
        uses: reviewdog/action-yamllint@8d79c3d034667db2792e328936811ed44953d691 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}
          yamllint_flags: -c .github/linters/.yaml-lint.yml .

  Sobelow:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Compile
        run: mix compile

      - name: Sobelow
        run: mix sobelow

      # We run once to allow any compile warnings or things that
      # would interfere with the JSON output
      - name: Sobelow Sarif
        run: mix sobelow --format sarif > results.sarif

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # v3
        with:
          sarif_file: results.sarif

  Test:
    env:
      MIX_ENV: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Compile
        run: mix compile --all-warnings --warnings-as-errors

      - name: Start Docker Compose
        uses: ./.github/actions/start-docker-compose

      - name: Test
        run: mix test --all-warnings --cover --warnings-as-errors

name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
