---
jobs:
  Benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Cache Results
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
        with:
          key: benchmarks
          path: benchmark_results

      - name: Start Docker Compose
        uses: ./.github/actions/start-docker-compose

      - name: Benchmark
        run: mix benchmark

  Build_Documentation:
    name: Build (Documentation)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Build Docs
        run: mix docs

  Format_Elixir:
    name: Format (Elixir)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Format
        run: mix format ${{ github.event_name == 'pull_request' && '' || '--check-formatted' }}

      - if: ${{ github.event_name == 'pull_request' }}
        name: Suggest
        uses: reviewdog/action-suggester@db4abb16fbaabe386831e5addb7be1485d0d63d3 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          tool_name: mix

  Lint_Actions:
    name: Lint (Actions)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Lint
        uses: reviewdog/action-actionlint@7eeec1dd160c2301eb28e1568721837d084558ad # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Alex:
    name: Lint (Alex)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Lint
        uses: reviewdog/action-alex@73756e09c07d6025e86f0ac5605b65f2d4b4b78b # v1
        with:
          filter_mode: ${{ github.event_name == 'pull_request' && 'added' || 'nofilter' }}
          level: info
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_CSS:
    name: Lint (CSS)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Install Stylelint
        run: npm install stylelint stylelint-config-standard

      - name: Lint
        uses: reviewdog/action-stylelint@c1da6e75d890eba79f82a4294e867cbd720b52d9 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}
          stylelint_config: .github/linters/.stylelintrc.json

  Lint_Credo:
    name: Lint (Credo)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Credo
        run: mix credo

  Lint_Dialyzer:
    name: Lint (Dialyzer)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Dialyzer
        run: mix dialyzer

  Lint_Docker:
    name: Lint (Docker)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Lint
        uses: reviewdog/action-hadolint@73fec8b28091e5082c19df69815dd749d97b882a # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Doctor:
    name: Lint (Doctor)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Doctor
        run: mix doctor

  Lint_Javascript:
    name: Lint (Javascript)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Install Standard
        run: npm install eslint-config-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-n

      - name: Lint
        uses: reviewdog/action-eslint@9a6606695f1ef9709cce821919ca3b2a6d5e6bb5 # v1
        with:
          eslint_flags: --config .github/linters/.eslintrc.json .
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Markdown:
    name: Lint (Markdown)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Lint
        uses: reviewdog/action-markdownlint@28fb4224271253fedd5079b61de820d6228041fd # v0
        with:
          fail_on_error: true
          filter_mode: nofilter
          markdownlint_flags: -c .github/linters/.markdown-lint.yml .
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Misspell:
    name: Lint (Misspell)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Lint
        uses: reviewdog/action-misspell@ef8b22c1cca06c8d306fc6be302c3dab0f6ca12f # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          ignore: behaviour
          locale: US
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Shellcheck:
    name: Lint (Shellcheck)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Lint
        uses: reviewdog/action-shellcheck@ccaafec556ffa154f112bfcb7b9c9574190b7091 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Shfmt:
    name: Lint (shfmt)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Lint
        uses: reviewdog/action-shfmt@f59386f08bd9a24ac1a746e69f026ddc2ed06710 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter

  Lint_Yaml:
    name: Lint (Yaml)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Lint
        uses: reviewdog/action-yamllint@e09f07780388032a624e9eb44a23fd1bbb4052cc # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}
          yamllint_flags: -c .github/linters/.yaml-lint.yml .

  Security_Sobelow:
    name: Security (Sobelow)
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Compile
        run: mix compile

      - name: Sobelow
        run: mix sobelow

      # We run once to allow any compile warnings or things that
      # would interfere with the JSON output
      - name: Sobelow Sarif
        run: mix sobelow --skip --format sarif > results.sarif

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@f779452ac5af1c261dce0346a8f964149f49322b # v3
        with:
          sarif_file: results.sarif

  Test:
    env:
      MIX_ENV: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Compile
        run: mix compile --all-warnings --warnings-as-errors

      - name: Start Docker Compose
        uses: ./.github/actions/start-docker-compose

      - name: Test
        run: mix test --all-warnings --cover --warnings-as-errors

name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
