---

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Build Docs
        run: mix docs

  Format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Format
        run: mix format --check-formatted

  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint
        uses: github/super-linter/slim@v4

  Sobelow:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Sobelow
        uses: sobelow/action@v1

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

  Test:
    runs-on: ubuntu-latest

    services:
      cockroach:
        build:
        options: --entrypoint "/cockroach/start-insecure-local.sh"
        env:
          COCKROACH_USER: jumar
          COCKROACH_PASSWORD: jumar
        ports:
          - 26257:26257
          - 8080:8080

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Compile
        run: mix compile --all-warnings --warnings-as-errors

      - name: Test
        run: mix test --all-warnings --cover --warnings-as-errors
