---

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Format
        run: mix format --check-formatted

  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint
        uses: github/super-linter/slim@v4

  Sobelow:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Compile
        run: mix compile

      - name: Sabelow
        run: mix sobelow --strict --format sarif > ../results

      - name: Debug
        run: cat ../results

      - if: ${{ always() }}
        name: Upload Report
        uses: github/codeql-action/upload-sarif@v2
