---
jobs:
  Benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Cache Results
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          key: benchmarks
          path: benchmark_results

      - name: Start Docker Compose
        uses: ./.github/actions/start-docker-compose

      - name: Benchmark
        run: mix benchmark

  Docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Build Docs
        run: mix docs

  Format_Elixir:
    name: Format (Elixir)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Format
        run: mix format ${{ github.event_name == 'pull_request' && '' || '--check-formatted' }}

      - if: ${{ github.event_name == 'pull_request' }}
        name: Suggest
        uses: reviewdog/action-suggester@42b08604516990e201b3c21902cc13c6a0ee5fe8 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          tool_name: mix

  Lint_Actions:
    name: Lint (Actions)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-actionlint@2927e858b45218240af952feb1d702cf6365f39a # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Alex:
    name: Lint (Alex)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-alex@ac7b702763c2e35a8eadf1fe81cc6c82a5c1b455 # v1
        with:
          filter_mode: ${{ github.event_name == 'pull_request' && 'added' || 'nofilter' }}
          level: info
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_CSS:
    name: Lint (CSS)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install Stylelint
        run: npm install stylelint stylelint-config-standard

      - name: Lint
        uses: reviewdog/action-stylelint@f70205190f6cbffe5d2556cc7d4270c6084e9924 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}
          stylelint_config: .github/linters/.stylelintrc.json

  Lint_Credo:
    name: Lint (Credo)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Credo
        run: mix credo

  Lint_Docker:
    name: Lint (Docker)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-hadolint@66dae8a08183f1075386da9fff19a32512ddd31f # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Doctor:
    name: Lint (Doctor)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Doctor
        run: mix doctor

  Lint_Javascript:
    name: Lint (Javascript)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install Standard
        run: npm install eslint-config-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-n

      - name: Lint
        uses: reviewdog/action-eslint@da05f8bd5c8492adb664e57f7bb62ebe50d689e4 # v1
        with:
          eslint_flags: --config .github/linters/.eslintrc.json .
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Markdown:
    name: Lint (Markdown)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-markdownlint@2e07361ccbd82ffffcee50db2d35d1253fa2b6f8 # v0
        with:
          fail_on_error: true
          filter_mode: nofilter
          markdownlint_flags: -c .github/linters/.markdown-lint.yml .
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Misspell:
    name: Lint (Misspell)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-misspell@e4602ab781cd1c61e23a0c91316ab9e9a561da94 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          locale: US
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Shellcheck:
    name: Lint (Shellcheck)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-shellcheck@3546242c869924d13293e38e6289e00a26468e02 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}

  Lint_Shfmt:
    name: Lint (shfmt)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-shfmt@f59386f08bd9a24ac1a746e69f026ddc2ed06710 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter

  Lint_Yaml:
    name: Lint (Yaml)
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Lint
        uses: reviewdog/action-yamllint@bc37f456f657881f4a007caa6e243cef03ec8a84 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'local' }}
          yamllint_flags: -c .github/linters/.yaml-lint.yml .

  Sobelow:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Compile
        run: mix compile

      - name: Sobelow
        run: mix sobelow

      # We run once to allow any compile warnings or things that
      # would interfere with the JSON output
      - name: Sobelow Sarif
        run: mix sobelow --format sarif > results.sarif

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@23acc5c183826b7a8a97bce3cecc52db901f8251 # v3
        with:
          sarif_file: results.sarif

  Test:
    env:
      MIX_ENV: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir

      - name: Compile
        run: mix compile --all-warnings --warnings-as-errors

      - name: Start Docker Compose
        uses: ./.github/actions/start-docker-compose

      - name: Test
        run: mix test --all-warnings --cover --warnings-as-errors

name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
