---
jobs:
  Dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - id: appToken
        name: Get App Token
        uses: jnwng/github-app-installation-token-action@c54add4c02866dc41e106745ac6dcf5cdd6339e5 # v2
        with:
          appId: 875953
          installationId: 49559840
          privateKey: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - env:
          LOG_LEVEL: ${{ runner.debug && 'debug' || 'info' }}
        name: Renovate
        uses: renovatebot/github-action@13f127373fd3dc43b41b0979e37ba570d6c2b8f4 # v43.0.0
        with:
          configurationFile: .github/renovate-bot.json
          token: ${{ steps.appToken.outputs.token }}

name: Maintenance

on:
  push:
    paths:
      - .github/renovate-bot.json
      - .github/renovate.json
  schedule:
    - cron: "23 5 * * *"
  workflow_call:
  workflow_dispatch:
