---
jobs:
  Dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - id: appToken
        name: Get App Token
        uses: jnwng/github-app-installation-token-action@c54add4c02866dc41e106745ac6dcf5cdd6339e5 # v2
        with:
          appId: 875953
          installationId: 49559840
          privateKey: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - env:
          LOG_LEVEL: ${{ runner.debug && 'debug' || 'info' }}
        name: Renovate
        uses: renovatebot/github-action@19ba43e1bc58ed95c0ba205dee8b1bc0f27b630d # v42.0.0
        with:
          configurationFile: .github/renovate-bot.json
          token: ${{ steps.appToken.outputs.token }}

name: Maintenance

on:
  push:
    paths:
      - .github/renovate-bot.json
      - .github/renovate.json
  schedule:
    - cron: "23 5 * * *"
  workflow_call:
  workflow_dispatch:
