---

name: PR

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          allowed_prefixes: "feature,fix"
          prefix_case_sensitive: true
          min_length: 5
