---
jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        uses: deepakputhraya/action-pr-title@3864bebc79c5f829d25dd42d3c6579d040b0ef16 # v1.0.2
        with:
          allowed_prefixes: "fix,feat,chore,docs,perf,test"
          min_length: 5
          prefix_case_sensitive: true

name: PR

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
