---
jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload?.pull_request?.title;

            if (typeof title !== 'string') {
              core.info("Pull request data not in payload. Skipping PR title check.");
              return;
            }

            const REGEX = /^(feat!|fix!|fix|feat|chore|(fix|feat|chore)\(\w.*\)):\s(\[\w{1,8}-\d{1,8}\]|.*).*/;

            if (!REGEX.test(title)) {
              core.setFailed("Pull request title does not follow conventional commits");
              console.log(`
            Pull Request title "${title}" does not follow our [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) naming scheme.

            Please try renaming the PR to match one of these examples:

                chore: a small insignificant change
                fix: fix an existing feature
                feat: a new feature to release
                feat!: a breaking change

            Note: Adding ! (i.e. \`feat!:\`) represents a breaking change and will result in a SemVer major release.
                `.trim());
            }

name: PR

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
