---

name: Release

on:
  push:
    branches:
      - main

jobs:
  Please:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: elixir
          package-name: jumar
          extra-files: README.md
