app = "cockroach"

kill_signal = "SIGTERM"
kill_timeout = 300

primary_region = "den"
services = []

[build]
  image = "ghcr.io/btkostner/cockroach:1.0.0" # x-release-please-version

[checks]
  [checks.crdb]
    grace_period = "60s"
    interval = "15s"
    method = "get"
    path = "/health?ready=1"
    port = 8080
    protocol = "https"
    timeout = "10s"
    tls_skip_verify = true
    type = "http"

[deploy]
  strategy = "rolling"

[env]
  HOME = "/root"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network = true

[metrics]
  path = "/_status/vars"
  port = 8080
  protocol = "https"
  tls_skip_verify = true

[[mounts]]
  destination = "/cockroach/cockroach-data"
  source = "crdb_data"
